### ISSUE TITLE
Cannot find certificate authority

### ISSUE THREAD

**Issue by lucianoacsilva** [kkbankol-ibm/airexit#2]
Hello,

When executing the backend server, receive this error:

2019-05-30T14:42:29.954Z - error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Calling enrollment endpoint failed with error [Error: getaddrinfo ENOTFOUND ca.example.com ca.example.com:7054], stack=Error: Calling enrollment endpoint failed with error [Error: getaddrinfo ENOTFOUND ca.example.com ca.example.com:7054]

, despite the container of the CA already exists. Do you know what could be happening?

Regards

Luciano

**Comment by shm-tar** [comment]
I have the exact same issue here:
```
error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Calling enrollment
endpoint failed with error [Error: getaddrinfo ENOTFOUND ca.example.com ca.example.com:7054],
stack=Error: Calling enrollment endpoint failed with error [Error: getaddrinfo ENOTFOUND
ca.example.com ca.example.com:7054]
Error connecting to DB: one of _design, _reader is required for this request.
```

**Comment by roaraujo** [comment]
Me to:

2019-09-23T14:20:37.628Z - error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Calling enrollment endpoint failed with error [Error: getaddrinfo ENOTFOUND ca.example.com ca.example.com:7054], stack=Error: Calling enrollment endpoint failed with error [Error: getaddrinfo ENOTFOUND ca.example.com ca.example.com:7054]
    at ClientRequest.request.on (/home/rodrigo/Documentos/POC_BLOCK_FACE/airexit/node_modules/fabric-ca-client/lib/FabricCAClient.js:487:12)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error: Calling enrollment endpoint failed with error [Error: getaddrinfo ENOTFOUND ca.example.com ca.example.com:7054]
    at ClientRequest.request.on (/home/rodrigo/Documentos/POC_BLOCK_FACE/airexit/node_modules/fabric-ca-client/lib/FabricCAClient.js:487:12)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:9716) UnhandledPromiseRejectionWarning: Error: Failed to enroll admin
    at ca.enroll.then.then.catch (/home/rodrigo/Documentos/POC_BLOCK_FACE/airexit/server/api.js:531:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
